package cn.nsu.edu.qingshuyuxia.po;

import java.util.ArrayList;
import java.util.List;

public class PostsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public PostsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPostsnameIsNull() {
            addCriterion("postsName is null");
            return (Criteria) this;
        }

        public Criteria andPostsnameIsNotNull() {
            addCriterion("postsName is not null");
            return (Criteria) this;
        }

        public Criteria andPostsnameEqualTo(String value) {
            addCriterion("postsName =", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameNotEqualTo(String value) {
            addCriterion("postsName <>", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameGreaterThan(String value) {
            addCriterion("postsName >", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameGreaterThanOrEqualTo(String value) {
            addCriterion("postsName >=", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameLessThan(String value) {
            addCriterion("postsName <", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameLessThanOrEqualTo(String value) {
            addCriterion("postsName <=", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameLike(String value) {
            addCriterion("postsName like", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameNotLike(String value) {
            addCriterion("postsName not like", value, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameIn(List<String> values) {
            addCriterion("postsName in", values, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameNotIn(List<String> values) {
            addCriterion("postsName not in", values, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameBetween(String value1, String value2) {
            addCriterion("postsName between", value1, value2, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostsnameNotBetween(String value1, String value2) {
            addCriterion("postsName not between", value1, value2, "postsname");
            return (Criteria) this;
        }

        public Criteria andPostspicIsNull() {
            addCriterion("postsPic is null");
            return (Criteria) this;
        }

        public Criteria andPostspicIsNotNull() {
            addCriterion("postsPic is not null");
            return (Criteria) this;
        }

        public Criteria andPostspicEqualTo(String value) {
            addCriterion("postsPic =", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicNotEqualTo(String value) {
            addCriterion("postsPic <>", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicGreaterThan(String value) {
            addCriterion("postsPic >", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicGreaterThanOrEqualTo(String value) {
            addCriterion("postsPic >=", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicLessThan(String value) {
            addCriterion("postsPic <", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicLessThanOrEqualTo(String value) {
            addCriterion("postsPic <=", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicLike(String value) {
            addCriterion("postsPic like", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicNotLike(String value) {
            addCriterion("postsPic not like", value, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicIn(List<String> values) {
            addCriterion("postsPic in", values, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicNotIn(List<String> values) {
            addCriterion("postsPic not in", values, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicBetween(String value1, String value2) {
            addCriterion("postsPic between", value1, value2, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostspicNotBetween(String value1, String value2) {
            addCriterion("postsPic not between", value1, value2, "postspic");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridIsNull() {
            addCriterion("postsAuthorId is null");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridIsNotNull() {
            addCriterion("postsAuthorId is not null");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridEqualTo(Integer value) {
            addCriterion("postsAuthorId =", value, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridNotEqualTo(Integer value) {
            addCriterion("postsAuthorId <>", value, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridGreaterThan(Integer value) {
            addCriterion("postsAuthorId >", value, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridGreaterThanOrEqualTo(Integer value) {
            addCriterion("postsAuthorId >=", value, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridLessThan(Integer value) {
            addCriterion("postsAuthorId <", value, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridLessThanOrEqualTo(Integer value) {
            addCriterion("postsAuthorId <=", value, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridIn(List<Integer> values) {
            addCriterion("postsAuthorId in", values, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridNotIn(List<Integer> values) {
            addCriterion("postsAuthorId not in", values, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridBetween(Integer value1, Integer value2) {
            addCriterion("postsAuthorId between", value1, value2, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andPostsauthoridNotBetween(Integer value1, Integer value2) {
            addCriterion("postsAuthorId not between", value1, value2, "postsauthorid");
            return (Criteria) this;
        }

        public Criteria andWheremdIsNull() {
            addCriterion("whereMd is null");
            return (Criteria) this;
        }

        public Criteria andWheremdIsNotNull() {
            addCriterion("whereMd is not null");
            return (Criteria) this;
        }

        public Criteria andWheremdEqualTo(Integer value) {
            addCriterion("whereMd =", value, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdNotEqualTo(Integer value) {
            addCriterion("whereMd <>", value, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdGreaterThan(Integer value) {
            addCriterion("whereMd >", value, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdGreaterThanOrEqualTo(Integer value) {
            addCriterion("whereMd >=", value, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdLessThan(Integer value) {
            addCriterion("whereMd <", value, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdLessThanOrEqualTo(Integer value) {
            addCriterion("whereMd <=", value, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdIn(List<Integer> values) {
            addCriterion("whereMd in", values, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdNotIn(List<Integer> values) {
            addCriterion("whereMd not in", values, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdBetween(Integer value1, Integer value2) {
            addCriterion("whereMd between", value1, value2, "wheremd");
            return (Criteria) this;
        }

        public Criteria andWheremdNotBetween(Integer value1, Integer value2) {
            addCriterion("whereMd not between", value1, value2, "wheremd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 27 20:07:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}