package cn.nsu.edu.qingshuyuxia.mapper;

import cn.nsu.edu.qingshuyuxia.po.ArticleLabel;
import cn.nsu.edu.qingshuyuxia.po.ArticleLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int countByExample(ArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int deleteByExample(ArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int insert(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int insertSelective(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    List<ArticleLabel> selectByExample(ArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    ArticleLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") ArticleLabel record, @Param("example") ArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int updateByExample(@Param("record") ArticleLabel record, @Param("example") ArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int updateByPrimaryKeySelective(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    int updateByPrimaryKey(ArticleLabel record);
}