package cn.nsu.edu.qingshuyuxia.mapper;

import cn.nsu.edu.qingshuyuxia.po.Posts;
import cn.nsu.edu.qingshuyuxia.po.PostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int countByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int deleteByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int insert(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int insertSelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    List<Posts> selectByExampleWithBLOBs(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    List<Posts> selectByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    Posts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int updateByExample(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int updateByPrimaryKeySelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Dec 27 20:07:22 CST 2016
     */
    int updateByPrimaryKey(Posts record);
}