package cn.nsu.edu.qingshuyuxia.po;

public class ArticleLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.id
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.articleId
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.labelId
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    private Integer labelid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.id
     *
     * @return the value of article_label.id
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.id
     *
     * @param id the value for article_label.id
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.articleId
     *
     * @return the value of article_label.articleId
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.articleId
     *
     * @param articleid the value for article_label.articleId
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.labelId
     *
     * @return the value of article_label.labelId
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    public Integer getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.labelId
     *
     * @param labelid the value for article_label.labelId
     *
     * @mbggenerated Mon Feb 20 16:38:59 CST 2017
     */
    public void setLabelid(Integer labelid) {
        this.labelid = labelid;
    }
}