package cn.nsu.edu.qingshuyuxia.po;

public class Label {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.id
     *
     * @mbggenerated Tue Feb 21 10:29:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.name
     *
     * @mbggenerated Tue Feb 21 10:29:59 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.id
     *
     * @return the value of label.id
     *
     * @mbggenerated Tue Feb 21 10:29:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.id
     *
     * @param id the value for label.id
     *
     * @mbggenerated Tue Feb 21 10:29:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.name
     *
     * @return the value of label.name
     *
     * @mbggenerated Tue Feb 21 10:29:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.name
     *
     * @param name the value for label.name
     *
     * @mbggenerated Tue Feb 21 10:29:59 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}