package cn.nsu.edu.qingshuyuxia.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReviewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public ReviewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andArticleidIsNull() {
            addCriterion("articleId is null");
            return (Criteria) this;
        }

        public Criteria andArticleidIsNotNull() {
            addCriterion("articleId is not null");
            return (Criteria) this;
        }

        public Criteria andArticleidEqualTo(Integer value) {
            addCriterion("articleId =", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotEqualTo(Integer value) {
            addCriterion("articleId <>", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidGreaterThan(Integer value) {
            addCriterion("articleId >", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleId >=", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidLessThan(Integer value) {
            addCriterion("articleId <", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidLessThanOrEqualTo(Integer value) {
            addCriterion("articleId <=", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidIn(List<Integer> values) {
            addCriterion("articleId in", values, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotIn(List<Integer> values) {
            addCriterion("articleId not in", values, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidBetween(Integer value1, Integer value2) {
            addCriterion("articleId between", value1, value2, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotBetween(Integer value1, Integer value2) {
            addCriterion("articleId not between", value1, value2, "articleid");
            return (Criteria) this;
        }

        public Criteria andReplyidIsNull() {
            addCriterion("replyId is null");
            return (Criteria) this;
        }

        public Criteria andReplyidIsNotNull() {
            addCriterion("replyId is not null");
            return (Criteria) this;
        }

        public Criteria andReplyidEqualTo(Integer value) {
            addCriterion("replyId =", value, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidNotEqualTo(Integer value) {
            addCriterion("replyId <>", value, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidGreaterThan(Integer value) {
            addCriterion("replyId >", value, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("replyId >=", value, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidLessThan(Integer value) {
            addCriterion("replyId <", value, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidLessThanOrEqualTo(Integer value) {
            addCriterion("replyId <=", value, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidIn(List<Integer> values) {
            addCriterion("replyId in", values, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidNotIn(List<Integer> values) {
            addCriterion("replyId not in", values, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidBetween(Integer value1, Integer value2) {
            addCriterion("replyId between", value1, value2, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyidNotBetween(Integer value1, Integer value2) {
            addCriterion("replyId not between", value1, value2, "replyid");
            return (Criteria) this;
        }

        public Criteria andReplyusernameIsNull() {
            addCriterion("replyUserName is null");
            return (Criteria) this;
        }

        public Criteria andReplyusernameIsNotNull() {
            addCriterion("replyUserName is not null");
            return (Criteria) this;
        }

        public Criteria andReplyusernameEqualTo(String value) {
            addCriterion("replyUserName =", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameNotEqualTo(String value) {
            addCriterion("replyUserName <>", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameGreaterThan(String value) {
            addCriterion("replyUserName >", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameGreaterThanOrEqualTo(String value) {
            addCriterion("replyUserName >=", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameLessThan(String value) {
            addCriterion("replyUserName <", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameLessThanOrEqualTo(String value) {
            addCriterion("replyUserName <=", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameLike(String value) {
            addCriterion("replyUserName like", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameNotLike(String value) {
            addCriterion("replyUserName not like", value, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameIn(List<String> values) {
            addCriterion("replyUserName in", values, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameNotIn(List<String> values) {
            addCriterion("replyUserName not in", values, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameBetween(String value1, String value2) {
            addCriterion("replyUserName between", value1, value2, "replyusername");
            return (Criteria) this;
        }

        public Criteria andReplyusernameNotBetween(String value1, String value2) {
            addCriterion("replyUserName not between", value1, value2, "replyusername");
            return (Criteria) this;
        }

        public Criteria andCommentuseridIsNull() {
            addCriterion("commentUserId is null");
            return (Criteria) this;
        }

        public Criteria andCommentuseridIsNotNull() {
            addCriterion("commentUserId is not null");
            return (Criteria) this;
        }

        public Criteria andCommentuseridEqualTo(Integer value) {
            addCriterion("commentUserId =", value, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridNotEqualTo(Integer value) {
            addCriterion("commentUserId <>", value, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridGreaterThan(Integer value) {
            addCriterion("commentUserId >", value, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentUserId >=", value, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridLessThan(Integer value) {
            addCriterion("commentUserId <", value, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridLessThanOrEqualTo(Integer value) {
            addCriterion("commentUserId <=", value, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridIn(List<Integer> values) {
            addCriterion("commentUserId in", values, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridNotIn(List<Integer> values) {
            addCriterion("commentUserId not in", values, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridBetween(Integer value1, Integer value2) {
            addCriterion("commentUserId between", value1, value2, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("commentUserId not between", value1, value2, "commentuserid");
            return (Criteria) this;
        }

        public Criteria andCommentusernameIsNull() {
            addCriterion("commentUserName is null");
            return (Criteria) this;
        }

        public Criteria andCommentusernameIsNotNull() {
            addCriterion("commentUserName is not null");
            return (Criteria) this;
        }

        public Criteria andCommentusernameEqualTo(String value) {
            addCriterion("commentUserName =", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameNotEqualTo(String value) {
            addCriterion("commentUserName <>", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameGreaterThan(String value) {
            addCriterion("commentUserName >", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameGreaterThanOrEqualTo(String value) {
            addCriterion("commentUserName >=", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameLessThan(String value) {
            addCriterion("commentUserName <", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameLessThanOrEqualTo(String value) {
            addCriterion("commentUserName <=", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameLike(String value) {
            addCriterion("commentUserName like", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameNotLike(String value) {
            addCriterion("commentUserName not like", value, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameIn(List<String> values) {
            addCriterion("commentUserName in", values, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameNotIn(List<String> values) {
            addCriterion("commentUserName not in", values, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameBetween(String value1, String value2) {
            addCriterion("commentUserName between", value1, value2, "commentusername");
            return (Criteria) this;
        }

        public Criteria andCommentusernameNotBetween(String value1, String value2) {
            addCriterion("commentUserName not between", value1, value2, "commentusername");
            return (Criteria) this;
        }

        public Criteria andReviewcontentIsNull() {
            addCriterion("reviewContent is null");
            return (Criteria) this;
        }

        public Criteria andReviewcontentIsNotNull() {
            addCriterion("reviewContent is not null");
            return (Criteria) this;
        }

        public Criteria andReviewcontentEqualTo(String value) {
            addCriterion("reviewContent =", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentNotEqualTo(String value) {
            addCriterion("reviewContent <>", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentGreaterThan(String value) {
            addCriterion("reviewContent >", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentGreaterThanOrEqualTo(String value) {
            addCriterion("reviewContent >=", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentLessThan(String value) {
            addCriterion("reviewContent <", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentLessThanOrEqualTo(String value) {
            addCriterion("reviewContent <=", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentLike(String value) {
            addCriterion("reviewContent like", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentNotLike(String value) {
            addCriterion("reviewContent not like", value, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentIn(List<String> values) {
            addCriterion("reviewContent in", values, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentNotIn(List<String> values) {
            addCriterion("reviewContent not in", values, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentBetween(String value1, String value2) {
            addCriterion("reviewContent between", value1, value2, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andReviewcontentNotBetween(String value1, String value2) {
            addCriterion("reviewContent not between", value1, value2, "reviewcontent");
            return (Criteria) this;
        }

        public Criteria andDataIsNull() {
            addCriterion("data is null");
            return (Criteria) this;
        }

        public Criteria andDataIsNotNull() {
            addCriterion("data is not null");
            return (Criteria) this;
        }

        public Criteria andDataEqualTo(Date value) {
            addCriterionForJDBCDate("data =", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotEqualTo(Date value) {
            addCriterionForJDBCDate("data <>", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThan(Date value) {
            addCriterionForJDBCDate("data >", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data >=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThan(Date value) {
            addCriterionForJDBCDate("data <", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data <=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataIn(List<Date> values) {
            addCriterionForJDBCDate("data in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotIn(List<Date> values) {
            addCriterionForJDBCDate("data not in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data not between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andSystemIsNull() {
            addCriterion("system is null");
            return (Criteria) this;
        }

        public Criteria andSystemIsNotNull() {
            addCriterion("system is not null");
            return (Criteria) this;
        }

        public Criteria andSystemEqualTo(String value) {
            addCriterion("system =", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotEqualTo(String value) {
            addCriterion("system <>", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThan(String value) {
            addCriterion("system >", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThanOrEqualTo(String value) {
            addCriterion("system >=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThan(String value) {
            addCriterion("system <", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThanOrEqualTo(String value) {
            addCriterion("system <=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLike(String value) {
            addCriterion("system like", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotLike(String value) {
            addCriterion("system not like", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemIn(List<String> values) {
            addCriterion("system in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotIn(List<String> values) {
            addCriterion("system not in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemBetween(String value1, String value2) {
            addCriterion("system between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotBetween(String value1, String value2) {
            addCriterion("system not between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andBrowserIsNull() {
            addCriterion("browser is null");
            return (Criteria) this;
        }

        public Criteria andBrowserIsNotNull() {
            addCriterion("browser is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserEqualTo(String value) {
            addCriterion("browser =", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotEqualTo(String value) {
            addCriterion("browser <>", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserGreaterThan(String value) {
            addCriterion("browser >", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserGreaterThanOrEqualTo(String value) {
            addCriterion("browser >=", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserLessThan(String value) {
            addCriterion("browser <", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserLessThanOrEqualTo(String value) {
            addCriterion("browser <=", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserLike(String value) {
            addCriterion("browser like", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotLike(String value) {
            addCriterion("browser not like", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserIn(List<String> values) {
            addCriterion("browser in", values, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotIn(List<String> values) {
            addCriterion("browser not in", values, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserBetween(String value1, String value2) {
            addCriterion("browser between", value1, value2, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotBetween(String value1, String value2) {
            addCriterion("browser not between", value1, value2, "browser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 15 06:18:15 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated Wed Feb 15 06:18:15 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}